server:
  port: 80
  servlet:
    context-path: /
spring:
  cache:
    redis:
      cache-null-values: true
  #redis相关配置
  redis:
    host: 192.168.12.128
    port: 7001
#    password:
    database: 0
    timeout: 10s
    # 配置文件中添加 lettuce.pool 相关配置，则会使用到lettuce连接池
    lettuce:
     pool:
       max-active: 200
       min-idle: 0
       max-idle: 10
       max-wait: -1ms
    #    jedis:
    #      pool:
    #        max-wait: 10000 #最大阻塞等待时间
    #        max-active: 100
    #        max-idle: 20
    #        min-idle: 0